CREATE TABLE Person (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email varchar(100) NOT NULL,
    password varchar(100) NOT NULL,
    age int CHECK(age > 0 and age < 120)
);

INSERT INTO Person (email, password, age)
VALUES
('ivanoff256@mail.ru', 'qwerty123', 24),
('petroff256@mail.ru', 'qwerty123', 34),
('smirnoff256@mail.ru', 'qwerty123', 37),
('alekseev256@mail.ru', 'qwerty123', 45),
('andreev256@mail.ru', 'qwerty123', 18)